check-leaks: true
color: true
extension:
  - 'js'
file:
  # - 
full-trace: true
growl: true
recursive: false
reporter: 'spec'
# require: '@babel/register'
require: 'register-babel.js'
# spec: 'test/**/**/*-test.js'
watch: true
